#pragma once

#include "topic_bus.h"

#define MSG_RC_COMMAND_TOPIC_DEPTH 1U
#define MSG_RC_COMMAND_TOPIC_MAX_WAITER 8U
#define MSG_RC_COMMAND_TOPIC_NAME "/rc_command"

#define MSG_INS_TOPIC_DEPTH 1U
#define MSG_INS_TOPIC_MAX_WAITER 8U
#define MSG_INS_TOPIC_NAME "/ins"

#define MSG_TOPIC_BUS_TEST_CMD_TOPIC_DEPTH 1U
#define MSG_TOPIC_BUS_TEST_CMD_TOPIC_MAX_WAITER 2U
#define MSG_TOPIC_BUS_TEST_CMD_TOPIC_NAME "/topic_bus_test_cmd"

#define MSG_TOPIC_BUS_TEST_STATE_TOPIC_DEPTH 4U
#define MSG_TOPIC_BUS_TEST_STATE_TOPIC_MAX_WAITER 2U
#define MSG_TOPIC_BUS_TEST_STATE_TOPIC_NAME "/topic_bus_test_state"

#define MSG_TOPIC_BUS_TEST_STATE_AUX_TOPIC_DEPTH 4U
#define MSG_TOPIC_BUS_TEST_STATE_AUX_TOPIC_MAX_WAITER 2U
#define MSG_TOPIC_BUS_TEST_STATE_AUX_TOPIC_NAME "/topic_bus_test_state_aux"

typedef enum
{
    APP_TOPICS_RC_COMMAND = 0,
    APP_TOPICS_INS,
    APP_TOPICS_TOPIC_BUS_TEST_CMD,
    APP_TOPICS_TOPIC_BUS_TEST_STATE,
    APP_TOPICS_TOPIC_BUS_TEST_STATE_AUX,
    APP_TOPICS_MAX,
} appTopics_e;

moduleTopic_t *appTopicsGet(appTopics_e topic_id);
