#pragma once

#include "general_math.h"

#ifndef USER_RMD_V2_X6_CAN_ID_CONFIG_ENABLE
#define USER_RMD_V2_X6_CAN_ID_CONFIG_ENABLE 0U
#endif

#ifndef USER_RMD_V2_X6_CAN_ID_CONFIG_TARGET_CAN_ID
#define USER_RMD_V2_X6_CAN_ID_CONFIG_TARGET_CAN_ID 2U
#endif

#ifndef USER_RMD_V2_X6_CAN_ID_CONFIG_SEND_PERIOD_MS
#define USER_RMD_V2_X6_CAN_ID_CONFIG_SEND_PERIOD_MS 1000U
#endif

#ifndef USER_RMD_V2_X6_CAN_ID_CONFIG_REPLY_TIMEOUT_MS
#define USER_RMD_V2_X6_CAN_ID_CONFIG_REPLY_TIMEOUT_MS 100U
#endif
