#ifndef BSP_DEF_H
#define BSP_DEF_H

// GPIO
#define BSP_GPIO_MAX_INSTANCE_NUM 10U

// UART
#define BSP_UART_MAX_INSTANCE_NUM 3U
#define BSP_UART_RX_BUFFER_SIZE 64U
#define BSP_UART_TX_BLOCKING_TIMEOUT 100U

// SPI
#define BSP_SPI_MAX_INSTANCE_NUM 2U
#define BSP_SPI_BLOCKING_TIMEOUT 100U

// CAN
#define BSP_CAN_MAX_INSTANCE_NUM 2U
#define BSP_CAN_SINGLE_MAX_DEVICE_NUM 8U

// I2C
#define BSP_I2C_MAX_INSTANCE_NUM 2U
#define BSP_I2C_SINGLE_MAX_SLAVE_NUM 8U
#define BSP_I2C_BLOCKING_TIMEOUT 100U

#endif // !BSP_DEF_H