#ifndef BSP_DEF_H
#define BSP_DEF_H

// GPIO
#define BSP_GPIO_MAX_INSTANCE_NUM 10

// UART
#define BSP_UART_MAX_INSTANCE_NUM 3
#define BSP_UART_RX_BUFFER_SIZE 128
#define BSP_UART_TX_BLOCKING_TIMEOUT 100

// SPI
#define BSP_SPI_MAX_INSTANCE_NUM 2
#define BSP_SPI_BLOCKING_TIMEOUT 100

// CAN
#define BSP_CAN_MAX_INSTANCE_NUM 2
#define BSP_CAN_SINGLE_MAX_DEVICE_NUM 8

#endif // !BSP_DEF_H